"""Pure style definitions and helpers for karaoke subtitle stages."""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Mapping

DEFAULT_STYLE_KEY = "verse"
SUPPORTED_EFFECTS = ("highlight", "fade_in", "bounce", "flash", "none")


@dataclass(frozen=True)
class KaraokeStyle:
    r"""
    One ASS style definition.
    primary_color   = not-yet-sung text color   (\1c)  &HBBGGRR& format
    secondary_color = progressive fill color    (\2c)  filled by \kf
    outline_color   = border                    (\3c)
    back_color      = shadow/background         (\4c)
    """

    name: str
    fontname: str
    fontsize: int
    bold: bool
    italic: bool
    primary_color: str
    secondary_color: str
    outline_color: str
    back_color: str
    outline: float
    shadow: float
    alignment: int
    margin_v: int
    border_style: int = 1
    flash_on_highlight: bool = False


@dataclass(frozen=True)
class StylePreset:
    id: str
    label: str
    version: int
    description: str
    styles: Mapping[str, KaraokeStyle]
    effects: tuple[str, ...] = SUPPORTED_EFFECTS
    effect_profile_id: str = "clean_sweep"


@dataclass(frozen=True)
class AnimationProfile:
    id: str
    label: str
    safety: str
    karaoke_tag: str
    line_effects: tuple[str, ...]
    word_effects: tuple[str, ...]
    layer_strategy: str
    max_extra_layers: int
    motion_intensity: str
    description: str


def _c(r: int, g: int, b: int, a: int = 0) -> str:
    """Convert RGBA to ASS &HAABBGGRR format."""
    return f"&H{a:02X}{b:02X}{g:02X}{r:02X}"


ANIMATION_PROFILES: dict[str, AnimationProfile] = {
    "clean_sweep": AnimationProfile("clean_sweep", "Clean Sweep", "safe", "kf", ("fade",), ("sweep",), "single", 0, "none", "Current readable left-to-right karaoke sweep."),
    "instant": AnimationProfile("instant", "Instant Fill", "safe", "k", ("fade",), ("instant",), "single", 0, "none", "Classic instant karaoke color switch."),
    "outline_pop": AnimationProfile("outline_pop", "Outline Pop", "safe", "ko", ("fade",), ("outline_pop",), "single", 0, "low", "Outline appears at the vocal attack for a crisp pop."),
    "soft_glow": AnimationProfile("soft_glow", "Soft Glow", "safe", "kf", ("fade",), ("glow_pulse",), "single", 0, "low", "Readable sweep with a restrained outline glow pulse."),
    "bounce_word": AnimationProfile("bounce_word", "Bounce Word", "safe", "kf", ("fade",), ("scale_pop",), "single", 0, "medium", "Small scale bounce on each highlighted word."),
    "chorus_bloom": AnimationProfile("chorus_bloom", "Chorus Bloom", "layered", "kf", ("fade",), ("glow_pulse", "echo_shadow"), "extra_layer", 1, "medium", "Future chorus-focused bloom using one extra glow layer."),
    "syllable_float": AnimationProfile("syllable_float", "Syllable Float", "layered", "kf", ("fade",), ("float",), "per_syllable", 1, "medium", "Future per-syllable vertical motion."),
    "typewriter_clip": AnimationProfile("typewriter_clip", "Typewriter Clip", "layered", "kf", ("fade",), ("clip_reveal",), "clip", 1, "low", "Future rectangular clip reveal."),
    "aegisub_templater": AnimationProfile("aegisub_templater", "Aegisub Templater", "experimental", "kf", ("template",), ("inline_fx",), "templater", 99, "high", "Future Automation/Lua templater export profile."),
}


DEFAULT_STYLES: dict[str, KaraokeStyle] = {
    "verse": KaraokeStyle(
        name="Verse",
        fontname="Segoe UI Bold",
        fontsize=52,
        bold=True,
        italic=False,
        primary_color=_c(220, 220, 220),
        secondary_color=_c(0, 220, 255),
        outline_color=_c(0, 0, 0),
        back_color=_c(0, 0, 0, 80),
        outline=2.5,
        shadow=1.5,
        alignment=2,
        margin_v=40,
    ),
    "chorus": KaraokeStyle(
        name="Chorus",
        fontname="Segoe UI Bold",
        fontsize=64,
        bold=True,
        italic=False,
        primary_color=_c(255, 255, 255),
        secondary_color=_c(0, 200, 255),
        outline_color=_c(0, 60, 120),
        back_color=_c(0, 0, 0, 60),
        outline=3.0,
        shadow=2.0,
        alignment=2,
        margin_v=40,
    ),
    "bridge": KaraokeStyle(
        name="Bridge",
        fontname="Segoe UI Bold",
        fontsize=50,
        bold=True,
        italic=True,
        primary_color=_c(210, 210, 255),
        secondary_color=_c(200, 100, 255),
        outline_color=_c(0, 0, 0),
        back_color=_c(0, 0, 0, 80),
        outline=2.5,
        shadow=1.5,
        alignment=2,
        margin_v=40,
    ),
    "intro": KaraokeStyle(
        name="Intro",
        fontname="Segoe UI Bold",
        fontsize=40,
        bold=False,
        italic=False,
        primary_color=_c(180, 180, 180),
        secondary_color=_c(200, 200, 200),
        outline_color=_c(0, 0, 0),
        back_color=_c(0, 0, 0, 100),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=40,
    ),
    "outro": KaraokeStyle(
        name="Outro",
        fontname="Segoe UI Bold",
        fontsize=40,
        bold=False,
        italic=False,
        primary_color=_c(180, 180, 180),
        secondary_color=_c(200, 200, 200),
        outline_color=_c(0, 0, 0),
        back_color=_c(0, 0, 0, 100),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=40,
    ),
    "ad_lib": KaraokeStyle(
        name="AdLib",
        fontname="Segoe UI Bold",
        fontsize=38,
        bold=True,
        italic=True,
        primary_color=_c(200, 255, 200),
        secondary_color=_c(50, 255, 100),
        outline_color=_c(0, 60, 0),
        back_color=_c(0, 0, 0, 100),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=40,
    ),
}

NEON_STYLES: dict[str, KaraokeStyle] = {
    k: KaraokeStyle(
        name=v.name,
        fontname="Segoe UI Bold",
        fontsize=v.fontsize + 4,
        bold=True,
        italic=v.italic,
        primary_color=_c(40, 40, 40),
        secondary_color=_c(0, 255, 180),
        outline_color=_c(0, 200, 120),
        back_color=_c(0, 0, 0, 60),
        outline=3.0,
        shadow=0.0,
        alignment=v.alignment,
        margin_v=v.margin_v,
    )
    for k, v in DEFAULT_STYLES.items()
}

NEON_STYLES["chorus"] = KaraokeStyle(
    name="Chorus",
    fontname="Segoe UI Bold",
    fontsize=68,
    bold=True,
    italic=False,
    primary_color=_c(60, 60, 60),
    secondary_color=_c(255, 220, 0),
    outline_color=_c(180, 140, 0),
    back_color=_c(0, 0, 0, 60),
    outline=3.5,
    shadow=0.0,
    alignment=2,
    margin_v=40,
)

CYBERPUNK_STYLES: dict[str, KaraokeStyle] = {
    "verse": KaraokeStyle(
        name="Verse",
        fontname="Segoe UI Bold",
        fontsize=52,
        bold=True,
        italic=False,
        primary_color=_c(123, 47, 190),
        secondary_color=_c(0, 245, 255),
        outline_color=_c(0, 0, 0),
        back_color=_c(0, 0, 0, 150),
        outline=2.5,
        shadow=1.5,
        alignment=2,
        margin_v=50,
        border_style=3,
        flash_on_highlight=True,
    ),
    "chorus": KaraokeStyle(
        name="Chorus",
        fontname="Segoe UI Bold",
        fontsize=64,
        bold=True,
        italic=False,
        primary_color=_c(255, 255, 255),
        secondary_color=_c(0, 245, 255),
        outline_color=_c(123, 47, 190),
        back_color=_c(0, 0, 0, 150),
        outline=3.0,
        shadow=2.0,
        alignment=2,
        margin_v=50,
        border_style=3,
        flash_on_highlight=True,
    ),
    "bridge": KaraokeStyle(
        name="Bridge",
        fontname="Segoe UI Bold",
        fontsize=52,
        bold=True,
        italic=True,
        primary_color=_c(180, 0, 180),
        secondary_color=_c(255, 255, 255),
        outline_color=_c(0, 0, 0),
        back_color=_c(0, 0, 0, 150),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=50,
        border_style=3,
        flash_on_highlight=False,
    ),
    "intro": DEFAULT_STYLES["intro"],
    "outro": DEFAULT_STYLES["outro"],
    "ad_lib": DEFAULT_STYLES["ad_lib"],
}

SECTION_CODED_STYLES: dict[str, KaraokeStyle] = {
    "intro": KaraokeStyle(
        name="Intro",
        fontname="Segoe UI Bold",
        fontsize=44,
        bold=False,
        italic=False,
        primary_color=_c(190, 220, 220),
        secondary_color=_c(90, 210, 220),
        outline_color=_c(0, 40, 48),
        back_color=_c(0, 0, 0, 90),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "verse": KaraokeStyle(
        name="Verse",
        fontname="Segoe UI Bold",
        fontsize=52,
        bold=True,
        italic=False,
        primary_color=_c(245, 245, 245),
        secondary_color=_c(255, 255, 255),
        outline_color=_c(20, 20, 20),
        back_color=_c(0, 0, 0, 80),
        outline=2.4,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "prechorus": KaraokeStyle(
        name="PreChorus",
        fontname="Segoe UI Bold",
        fontsize=54,
        bold=True,
        italic=False,
        primary_color=_c(255, 245, 190),
        secondary_color=_c(255, 220, 40),
        outline_color=_c(70, 54, 0),
        back_color=_c(0, 0, 0, 80),
        outline=2.5,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "chorus": KaraokeStyle(
        name="Chorus",
        fontname="Segoe UI Bold",
        fontsize=64,
        bold=True,
        italic=False,
        primary_color=_c(255, 235, 248),
        secondary_color=_c(255, 70, 190),
        outline_color=_c(90, 0, 52),
        back_color=_c(0, 0, 0, 70),
        outline=3.0,
        shadow=1.6,
        alignment=2,
        margin_v=42,
    ),
    "bridge": KaraokeStyle(
        name="Bridge",
        fontname="Segoe UI Bold",
        fontsize=52,
        bold=True,
        italic=True,
        primary_color=_c(220, 255, 225),
        secondary_color=_c(80, 220, 120),
        outline_color=_c(0, 55, 20),
        back_color=_c(0, 0, 0, 80),
        outline=2.5,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "drop": KaraokeStyle(
        name="Drop",
        fontname="Segoe UI Bold",
        fontsize=60,
        bold=True,
        italic=False,
        primary_color=_c(255, 235, 210),
        secondary_color=_c(255, 130, 40),
        outline_color=_c(80, 34, 0),
        back_color=_c(0, 0, 0, 80),
        outline=3.0,
        shadow=1.4,
        alignment=2,
        margin_v=42,
    ),
    "outro": KaraokeStyle(
        name="Outro",
        fontname="Segoe UI Bold",
        fontsize=44,
        bold=False,
        italic=False,
        primary_color=_c(190, 205, 235),
        secondary_color=_c(110, 150, 220),
        outline_color=_c(0, 25, 70),
        back_color=_c(0, 0, 0, 90),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "ad_lib": DEFAULT_STYLES["ad_lib"],
}

_SINGLE_STYLE_BASE = KaraokeStyle(
    name="Verse",
    fontname="Segoe UI Bold",
    fontsize=54,
    bold=True,
    italic=False,
    primary_color=_c(255, 248, 232),
    secondary_color=_c(255, 214, 92),
    outline_color=_c(84, 52, 5),
    back_color=_c(0, 0, 0, 78),
    outline=2.4,
    shadow=1.2,
    alignment=2,
    margin_v=42,
)

SINGLE_STYLE_KF_STYLES: dict[str, KaraokeStyle] = {
    key: KaraokeStyle(
        name=SECTION_CODED_STYLES.get(key, _SINGLE_STYLE_BASE).name,
        fontname=_SINGLE_STYLE_BASE.fontname,
        fontsize=_SINGLE_STYLE_BASE.fontsize,
        bold=_SINGLE_STYLE_BASE.bold,
        italic=_SINGLE_STYLE_BASE.italic,
        primary_color=_SINGLE_STYLE_BASE.primary_color,
        secondary_color=_SINGLE_STYLE_BASE.secondary_color,
        outline_color=_SINGLE_STYLE_BASE.outline_color,
        back_color=_SINGLE_STYLE_BASE.back_color,
        outline=_SINGLE_STYLE_BASE.outline,
        shadow=_SINGLE_STYLE_BASE.shadow,
        alignment=_SINGLE_STYLE_BASE.alignment,
        margin_v=_SINGLE_STYLE_BASE.margin_v,
        border_style=_SINGLE_STYLE_BASE.border_style,
        flash_on_highlight=_SINGLE_STYLE_BASE.flash_on_highlight,
    )
    for key in ("intro", "verse", "prechorus", "chorus", "bridge", "drop", "outro", "ad_lib")
}

AEGISUB_CLASSIC_BLUE_STYLES: dict[str, KaraokeStyle] = {
    "intro": KaraokeStyle(
        name="Intro",
        fontname="Segoe UI Bold",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(205, 225, 255),
        secondary_color=_c(110, 190, 255),
        outline_color=_c(0, 35, 95),
        back_color=_c(0, 0, 0, 90),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "verse": KaraokeStyle(
        name="Verse",
        fontname="Segoe UI Bold",
        fontsize=52,
        bold=True,
        italic=False,
        primary_color=_c(245, 250, 255),
        secondary_color=_c(60, 205, 255),
        outline_color=_c(0, 38, 90),
        back_color=_c(0, 0, 0, 80),
        outline=2.5,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "chorus": KaraokeStyle(
        name="Chorus",
        fontname="Segoe UI Bold",
        fontsize=64,
        bold=True,
        italic=False,
        primary_color=_c(255, 255, 255),
        secondary_color=_c(0, 240, 255),
        outline_color=_c(0, 78, 150),
        back_color=_c(0, 0, 0, 70),
        outline=3.0,
        shadow=1.6,
        alignment=2,
        margin_v=42,
    ),
    "bridge": KaraokeStyle(
        name="Bridge",
        fontname="Segoe UI Bold",
        fontsize=52,
        bold=True,
        italic=True,
        primary_color=_c(225, 235, 255),
        secondary_color=_c(140, 180, 255),
        outline_color=_c(0, 35, 95),
        back_color=_c(0, 0, 0, 80),
        outline=2.5,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "outro": KaraokeStyle(
        name="Outro",
        fontname="Segoe UI Bold",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(190, 210, 240),
        secondary_color=_c(100, 160, 220),
        outline_color=_c(0, 30, 80),
        back_color=_c(0, 0, 0, 90),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "ad_lib": KaraokeStyle(
        name="AdLib",
        fontname="Segoe UI Bold",
        fontsize=38,
        bold=True,
        italic=True,
        primary_color=_c(210, 245, 255),
        secondary_color=_c(80, 220, 255),
        outline_color=_c(0, 55, 80),
        back_color=_c(0, 0, 0, 100),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
}

AEGISUB_GOLD_CHORUS_STYLES: dict[str, KaraokeStyle] = {
    "intro": KaraokeStyle(
        name="Intro",
        fontname="Segoe UI Semibold",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(235, 228, 205),
        secondary_color=_c(255, 215, 120),
        outline_color=_c(82, 48, 0),
        back_color=_c(0, 0, 0, 90),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "verse": KaraokeStyle(
        name="Verse",
        fontname="Segoe UI Semibold",
        fontsize=52,
        bold=True,
        italic=False,
        primary_color=_c(255, 248, 232),
        secondary_color=_c(255, 214, 92),
        outline_color=_c(84, 52, 5),
        back_color=_c(0, 0, 0, 78),
        outline=2.4,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "prechorus": KaraokeStyle(
        name="PreChorus",
        fontname="Segoe UI Semibold",
        fontsize=56,
        bold=True,
        italic=False,
        primary_color=_c(255, 240, 188),
        secondary_color=_c(255, 184, 36),
        outline_color=_c(98, 56, 0),
        back_color=_c(0, 0, 0, 76),
        outline=2.6,
        shadow=1.3,
        alignment=2,
        margin_v=42,
    ),
    "chorus": KaraokeStyle(
        name="Chorus",
        fontname="Segoe UI Bold",
        fontsize=66,
        bold=True,
        italic=False,
        primary_color=_c(255, 255, 244),
        secondary_color=_c(255, 202, 28),
        outline_color=_c(122, 70, 0),
        back_color=_c(0, 0, 0, 70),
        outline=3.2,
        shadow=1.7,
        alignment=2,
        margin_v=42,
    ),
    "bridge": KaraokeStyle(
        name="Bridge",
        fontname="Segoe UI Semibold",
        fontsize=52,
        bold=True,
        italic=True,
        primary_color=_c(240, 225, 255),
        secondary_color=_c(205, 160, 255),
        outline_color=_c(70, 34, 92),
        back_color=_c(0, 0, 0, 82),
        outline=2.5,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "drop": KaraokeStyle(
        name="Drop",
        fontname="Segoe UI Bold",
        fontsize=62,
        bold=True,
        italic=False,
        primary_color=_c(255, 244, 210),
        secondary_color=_c(255, 148, 48),
        outline_color=_c(110, 42, 0),
        back_color=_c(0, 0, 0, 76),
        outline=3.0,
        shadow=1.5,
        alignment=2,
        margin_v=42,
    ),
    "outro": KaraokeStyle(
        name="Outro",
        fontname="Segoe UI Semibold",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(222, 208, 180),
        secondary_color=_c(220, 164, 72),
        outline_color=_c(72, 44, 0),
        back_color=_c(0, 0, 0, 92),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "ad_lib": KaraokeStyle(
        name="AdLib",
        fontname="Segoe UI Semibold",
        fontsize=38,
        bold=True,
        italic=True,
        primary_color=_c(255, 238, 196),
        secondary_color=_c(255, 190, 70),
        outline_color=_c(96, 50, 0),
        back_color=_c(0, 0, 0, 100),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
}

AEGISUB_ANIME_POP_STYLES: dict[str, KaraokeStyle] = {
    "intro": KaraokeStyle(
        name="Intro",
        fontname="Segoe UI Bold",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(255, 218, 245),
        secondary_color=_c(112, 230, 255),
        outline_color=_c(84, 22, 92),
        back_color=_c(0, 0, 0, 88),
        outline=2.1,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "verse": KaraokeStyle(
        name="Verse",
        fontname="Segoe UI Bold",
        fontsize=54,
        bold=True,
        italic=False,
        primary_color=_c(255, 245, 252),
        secondary_color=_c(64, 220, 255),
        outline_color=_c(92, 20, 98),
        back_color=_c(0, 0, 0, 78),
        outline=2.6,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "prechorus": KaraokeStyle(
        name="PreChorus",
        fontname="Segoe UI Bold",
        fontsize=56,
        bold=True,
        italic=False,
        primary_color=_c(255, 246, 198),
        secondary_color=_c(255, 230, 58),
        outline_color=_c(94, 58, 0),
        back_color=_c(0, 0, 0, 76),
        outline=2.6,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "chorus": KaraokeStyle(
        name="Chorus",
        fontname="Segoe UI Bold",
        fontsize=66,
        bold=True,
        italic=False,
        primary_color=_c(255, 255, 255),
        secondary_color=_c(255, 92, 202),
        outline_color=_c(112, 0, 80),
        back_color=_c(0, 0, 0, 70),
        outline=3.2,
        shadow=1.6,
        alignment=2,
        margin_v=42,
    ),
    "bridge": KaraokeStyle(
        name="Bridge",
        fontname="Segoe UI Bold",
        fontsize=52,
        bold=True,
        italic=True,
        primary_color=_c(222, 236, 255),
        secondary_color=_c(150, 125, 255),
        outline_color=_c(48, 35, 110),
        back_color=_c(0, 0, 0, 80),
        outline=2.5,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "drop": KaraokeStyle(
        name="Drop",
        fontname="Segoe UI Bold",
        fontsize=62,
        bold=True,
        italic=False,
        primary_color=_c(220, 255, 250),
        secondary_color=_c(0, 255, 196),
        outline_color=_c(0, 88, 82),
        back_color=_c(0, 0, 0, 76),
        outline=3.0,
        shadow=1.4,
        alignment=2,
        margin_v=42,
    ),
    "outro": KaraokeStyle(
        name="Outro",
        fontname="Segoe UI Bold",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(245, 210, 232),
        secondary_color=_c(240, 120, 210),
        outline_color=_c(72, 18, 84),
        back_color=_c(0, 0, 0, 90),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "ad_lib": KaraokeStyle(
        name="AdLib",
        fontname="Segoe UI Bold",
        fontsize=38,
        bold=True,
        italic=True,
        primary_color=_c(230, 255, 210),
        secondary_color=_c(130, 255, 80),
        outline_color=_c(38, 82, 0),
        back_color=_c(0, 0, 0, 100),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
}

AEGISUB_SOFT_PASTEL_STYLES: dict[str, KaraokeStyle] = {
    "intro": KaraokeStyle(
        name="Intro",
        fontname="Segoe UI Semibold",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(224, 236, 232),
        secondary_color=_c(168, 218, 210),
        outline_color=_c(54, 78, 86),
        back_color=_c(0, 0, 0, 82),
        outline=1.8,
        shadow=0.9,
        alignment=2,
        margin_v=42,
    ),
    "verse": KaraokeStyle(
        name="Verse",
        fontname="Segoe UI Semibold",
        fontsize=52,
        bold=True,
        italic=False,
        primary_color=_c(250, 248, 242),
        secondary_color=_c(160, 226, 204),
        outline_color=_c(58, 82, 88),
        back_color=_c(0, 0, 0, 72),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "chorus": KaraokeStyle(
        name="Chorus",
        fontname="Segoe UI Semibold",
        fontsize=62,
        bold=True,
        italic=False,
        primary_color=_c(255, 246, 250),
        secondary_color=_c(238, 170, 212),
        outline_color=_c(88, 58, 86),
        back_color=_c(0, 0, 0, 68),
        outline=2.3,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "bridge": KaraokeStyle(
        name="Bridge",
        fontname="Segoe UI Semibold",
        fontsize=52,
        bold=True,
        italic=True,
        primary_color=_c(238, 232, 255),
        secondary_color=_c(188, 170, 236),
        outline_color=_c(62, 58, 94),
        back_color=_c(0, 0, 0, 74),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "outro": KaraokeStyle(
        name="Outro",
        fontname="Segoe UI Semibold",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(224, 218, 230),
        secondary_color=_c(178, 170, 206),
        outline_color=_c(58, 60, 78),
        back_color=_c(0, 0, 0, 84),
        outline=1.8,
        shadow=0.9,
        alignment=2,
        margin_v=42,
    ),
    "ad_lib": KaraokeStyle(
        name="AdLib",
        fontname="Segoe UI Semibold",
        fontsize=38,
        bold=True,
        italic=True,
        primary_color=_c(232, 252, 222),
        secondary_color=_c(174, 230, 164),
        outline_color=_c(56, 82, 56),
        back_color=_c(0, 0, 0, 90),
        outline=1.8,
        shadow=0.9,
        alignment=2,
        margin_v=42,
    ),
}

AEGISUB_NIGHT_GLOW_STYLES: dict[str, KaraokeStyle] = {
    "intro": KaraokeStyle(
        name="Intro",
        fontname="Segoe UI Bold",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(188, 210, 255),
        secondary_color=_c(105, 150, 255),
        outline_color=_c(8, 18, 68),
        back_color=_c(0, 0, 0, 95),
        outline=2.2,
        shadow=0.8,
        alignment=2,
        margin_v=42,
    ),
    "verse": KaraokeStyle(
        name="Verse",
        fontname="Segoe UI Bold",
        fontsize=52,
        bold=True,
        italic=False,
        primary_color=_c(238, 244, 255),
        secondary_color=_c(98, 168, 255),
        outline_color=_c(10, 22, 76),
        back_color=_c(0, 0, 0, 84),
        outline=2.6,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "chorus": KaraokeStyle(
        name="Chorus",
        fontname="Segoe UI Bold",
        fontsize=64,
        bold=True,
        italic=False,
        primary_color=_c(255, 255, 255),
        secondary_color=_c(152, 92, 255),
        outline_color=_c(45, 16, 96),
        back_color=_c(0, 0, 0, 76),
        outline=3.2,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "bridge": KaraokeStyle(
        name="Bridge",
        fontname="Segoe UI Bold",
        fontsize=52,
        bold=True,
        italic=True,
        primary_color=_c(218, 224, 255),
        secondary_color=_c(198, 122, 255),
        outline_color=_c(34, 18, 86),
        back_color=_c(0, 0, 0, 84),
        outline=2.6,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "outro": KaraokeStyle(
        name="Outro",
        fontname="Segoe UI Bold",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(168, 188, 230),
        secondary_color=_c(98, 128, 210),
        outline_color=_c(8, 18, 68),
        back_color=_c(0, 0, 0, 96),
        outline=2.2,
        shadow=0.8,
        alignment=2,
        margin_v=42,
    ),
    "ad_lib": KaraokeStyle(
        name="AdLib",
        fontname="Segoe UI Bold",
        fontsize=38,
        bold=True,
        italic=True,
        primary_color=_c(212, 244, 255),
        secondary_color=_c(74, 220, 255),
        outline_color=_c(0, 68, 96),
        back_color=_c(0, 0, 0, 100),
        outline=2.2,
        shadow=0.8,
        alignment=2,
        margin_v=42,
    ),
}

AEGISUB_IMPACT_RED_STYLES: dict[str, KaraokeStyle] = {
    "intro": KaraokeStyle(
        name="Intro",
        fontname="Segoe UI Black",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(214, 214, 214),
        secondary_color=_c(238, 88, 58),
        outline_color=_c(74, 0, 0),
        back_color=_c(0, 0, 0, 92),
        outline=2.4,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "verse": KaraokeStyle(
        name="Verse",
        fontname="Segoe UI Black",
        fontsize=54,
        bold=True,
        italic=False,
        primary_color=_c(244, 244, 244),
        secondary_color=_c(235, 78, 52),
        outline_color=_c(78, 0, 0),
        back_color=_c(0, 0, 0, 82),
        outline=2.8,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "chorus": KaraokeStyle(
        name="Chorus",
        fontname="Segoe UI Black",
        fontsize=68,
        bold=True,
        italic=False,
        primary_color=_c(255, 255, 255),
        secondary_color=_c(255, 46, 26),
        outline_color=_c(112, 0, 0),
        back_color=_c(0, 0, 0, 72),
        outline=3.5,
        shadow=1.8,
        alignment=2,
        margin_v=42,
    ),
    "bridge": KaraokeStyle(
        name="Bridge",
        fontname="Segoe UI Black",
        fontsize=52,
        bold=True,
        italic=True,
        primary_color=_c(220, 220, 220),
        secondary_color=_c(255, 132, 70),
        outline_color=_c(94, 28, 0),
        back_color=_c(0, 0, 0, 84),
        outline=2.8,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "drop": KaraokeStyle(
        name="Drop",
        fontname="Segoe UI Black",
        fontsize=64,
        bold=True,
        italic=False,
        primary_color=_c(255, 232, 218),
        secondary_color=_c(255, 88, 0),
        outline_color=_c(116, 24, 0),
        back_color=_c(0, 0, 0, 76),
        outline=3.4,
        shadow=1.6,
        alignment=2,
        margin_v=42,
    ),
    "outro": KaraokeStyle(
        name="Outro",
        fontname="Segoe UI Black",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(194, 194, 194),
        secondary_color=_c(196, 52, 40),
        outline_color=_c(72, 0, 0),
        back_color=_c(0, 0, 0, 94),
        outline=2.4,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "ad_lib": KaraokeStyle(
        name="AdLib",
        fontname="Segoe UI Black",
        fontsize=38,
        bold=True,
        italic=True,
        primary_color=_c(255, 220, 210),
        secondary_color=_c(255, 110, 76),
        outline_color=_c(90, 10, 0),
        back_color=_c(0, 0, 0, 100),
        outline=2.4,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
}

AEGISUB_DUAL_VOCAL_STYLES: dict[str, KaraokeStyle] = {
    "intro": KaraokeStyle(
        name="Intro",
        fontname="Segoe UI Bold",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(198, 224, 238),
        secondary_color=_c(108, 210, 235),
        outline_color=_c(0, 58, 82),
        back_color=_c(0, 0, 0, 88),
        outline=2.1,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "verse": KaraokeStyle(
        name="Verse",
        fontname="Segoe UI Bold",
        fontsize=52,
        bold=True,
        italic=False,
        primary_color=_c(248, 252, 255),
        secondary_color=_c(72, 224, 246),
        outline_color=_c(0, 72, 96),
        back_color=_c(0, 0, 0, 78),
        outline=2.5,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "chorus": KaraokeStyle(
        name="Chorus",
        fontname="Segoe UI Bold",
        fontsize=64,
        bold=True,
        italic=False,
        primary_color=_c(255, 255, 255),
        secondary_color=_c(0, 198, 255),
        outline_color=_c(0, 78, 112),
        back_color=_c(0, 0, 0, 72),
        outline=3.0,
        shadow=1.5,
        alignment=2,
        margin_v=42,
    ),
    "bridge": KaraokeStyle(
        name="Bridge",
        fontname="Segoe UI Bold",
        fontsize=52,
        bold=True,
        italic=True,
        primary_color=_c(238, 226, 255),
        secondary_color=_c(184, 128, 255),
        outline_color=_c(62, 28, 98),
        back_color=_c(0, 0, 0, 80),
        outline=2.5,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "outro": KaraokeStyle(
        name="Outro",
        fontname="Segoe UI Bold",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(192, 218, 230),
        secondary_color=_c(100, 180, 210),
        outline_color=_c(0, 58, 82),
        back_color=_c(0, 0, 0, 90),
        outline=2.1,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "ad_lib": KaraokeStyle(
        name="AdLib",
        fontname="Segoe UI Bold",
        fontsize=38,
        bold=True,
        italic=True,
        primary_color=_c(218, 255, 220),
        secondary_color=_c(80, 242, 100),
        outline_color=_c(0, 78, 28),
        back_color=_c(0, 0, 0, 100),
        outline=2.1,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
}

AEGISUB_CLEAN_EDITORIAL_STYLES: dict[str, KaraokeStyle] = {
    "intro": KaraokeStyle(
        name="Intro",
        fontname="Arial",
        fontsize=40,
        bold=False,
        italic=False,
        primary_color=_c(206, 210, 214),
        secondary_color=_c(190, 194, 200),
        outline_color=_c(28, 32, 36),
        back_color=_c(0, 0, 0, 82),
        outline=1.8,
        shadow=0.8,
        alignment=2,
        margin_v=42,
    ),
    "verse": KaraokeStyle(
        name="Verse",
        fontname="Arial",
        fontsize=50,
        bold=True,
        italic=False,
        primary_color=_c(246, 246, 246),
        secondary_color=_c(230, 230, 230),
        outline_color=_c(30, 32, 34),
        back_color=_c(0, 0, 0, 72),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "chorus": KaraokeStyle(
        name="Chorus",
        fontname="Arial",
        fontsize=60,
        bold=True,
        italic=False,
        primary_color=_c(255, 255, 250),
        secondary_color=_c(232, 190, 90),
        outline_color=_c(70, 54, 18),
        back_color=_c(0, 0, 0, 70),
        outline=2.5,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "bridge": KaraokeStyle(
        name="Bridge",
        fontname="Arial",
        fontsize=50,
        bold=True,
        italic=True,
        primary_color=_c(226, 232, 238),
        secondary_color=_c(166, 184, 206),
        outline_color=_c(38, 46, 56),
        back_color=_c(0, 0, 0, 76),
        outline=2.0,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "outro": KaraokeStyle(
        name="Outro",
        fontname="Arial",
        fontsize=40,
        bold=False,
        italic=False,
        primary_color=_c(196, 198, 202),
        secondary_color=_c(168, 172, 178),
        outline_color=_c(28, 32, 36),
        back_color=_c(0, 0, 0, 84),
        outline=1.8,
        shadow=0.8,
        alignment=2,
        margin_v=42,
    ),
    "ad_lib": KaraokeStyle(
        name="AdLib",
        fontname="Arial",
        fontsize=36,
        bold=True,
        italic=True,
        primary_color=_c(226, 234, 226),
        secondary_color=_c(168, 202, 168),
        outline_color=_c(40, 58, 40),
        back_color=_c(0, 0, 0, 88),
        outline=1.8,
        shadow=0.8,
        alignment=2,
        margin_v=42,
    ),
}

AEGISUB_CYBER_MINIMAL_STYLES: dict[str, KaraokeStyle] = {
    "intro": KaraokeStyle(
        name="Intro",
        fontname="Segoe UI Semibold",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(176, 226, 238),
        secondary_color=_c(0, 212, 232),
        outline_color=_c(0, 52, 66),
        back_color=_c(0, 0, 0, 80),
        outline=2.0,
        shadow=0.0,
        alignment=2,
        margin_v=42,
    ),
    "verse": KaraokeStyle(
        name="Verse",
        fontname="Segoe UI Semibold",
        fontsize=52,
        bold=True,
        italic=False,
        primary_color=_c(232, 252, 255),
        secondary_color=_c(0, 238, 255),
        outline_color=_c(0, 58, 72),
        back_color=_c(0, 0, 0, 72),
        outline=2.4,
        shadow=0.0,
        alignment=2,
        margin_v=42,
    ),
    "chorus": KaraokeStyle(
        name="Chorus",
        fontname="Segoe UI Semibold",
        fontsize=64,
        bold=True,
        italic=False,
        primary_color=_c(255, 250, 255),
        secondary_color=_c(255, 64, 220),
        outline_color=_c(80, 0, 72),
        back_color=_c(0, 0, 0, 68),
        outline=2.8,
        shadow=0.0,
        alignment=2,
        margin_v=42,
    ),
    "bridge": KaraokeStyle(
        name="Bridge",
        fontname="Segoe UI Semibold",
        fontsize=52,
        bold=True,
        italic=True,
        primary_color=_c(220, 230, 255),
        secondary_color=_c(130, 116, 255),
        outline_color=_c(30, 28, 84),
        back_color=_c(0, 0, 0, 74),
        outline=2.4,
        shadow=0.0,
        alignment=2,
        margin_v=42,
    ),
    "outro": KaraokeStyle(
        name="Outro",
        fontname="Segoe UI Semibold",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(164, 206, 216),
        secondary_color=_c(0, 170, 196),
        outline_color=_c(0, 48, 62),
        back_color=_c(0, 0, 0, 82),
        outline=2.0,
        shadow=0.0,
        alignment=2,
        margin_v=42,
    ),
    "ad_lib": KaraokeStyle(
        name="AdLib",
        fontname="Segoe UI Semibold",
        fontsize=38,
        bold=True,
        italic=True,
        primary_color=_c(232, 255, 226),
        secondary_color=_c(88, 255, 150),
        outline_color=_c(0, 78, 46),
        back_color=_c(0, 0, 0, 88),
        outline=2.0,
        shadow=0.0,
        alignment=2,
        margin_v=42,
    ),
}

AEGISUB_STAGE_LIGHTS_STYLES: dict[str, KaraokeStyle] = {
    "intro": KaraokeStyle(
        name="Intro",
        fontname="Segoe UI Bold",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(210, 226, 255),
        secondary_color=_c(104, 166, 255),
        outline_color=_c(8, 38, 96),
        back_color=_c(0, 0, 0, 90),
        outline=2.2,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "verse": KaraokeStyle(
        name="Verse",
        fontname="Segoe UI Bold",
        fontsize=52,
        bold=True,
        italic=False,
        primary_color=_c(252, 252, 255),
        secondary_color=_c(88, 178, 255),
        outline_color=_c(8, 42, 98),
        back_color=_c(0, 0, 0, 80),
        outline=2.6,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "prechorus": KaraokeStyle(
        name="PreChorus",
        fontname="Segoe UI Bold",
        fontsize=56,
        bold=True,
        italic=False,
        primary_color=_c(232, 220, 255),
        secondary_color=_c(190, 94, 255),
        outline_color=_c(62, 16, 100),
        back_color=_c(0, 0, 0, 78),
        outline=2.8,
        shadow=1.3,
        alignment=2,
        margin_v=42,
    ),
    "chorus": KaraokeStyle(
        name="Chorus",
        fontname="Segoe UI Bold",
        fontsize=66,
        bold=True,
        italic=False,
        primary_color=_c(255, 255, 255),
        secondary_color=_c(255, 214, 70),
        outline_color=_c(98, 64, 0),
        back_color=_c(0, 0, 0, 72),
        outline=3.2,
        shadow=1.6,
        alignment=2,
        margin_v=42,
    ),
    "bridge": KaraokeStyle(
        name="Bridge",
        fontname="Segoe UI Bold",
        fontsize=52,
        bold=True,
        italic=True,
        primary_color=_c(255, 226, 250),
        secondary_color=_c(255, 94, 206),
        outline_color=_c(92, 12, 72),
        back_color=_c(0, 0, 0, 80),
        outline=2.6,
        shadow=1.2,
        alignment=2,
        margin_v=42,
    ),
    "drop": KaraokeStyle(
        name="Drop",
        fontname="Segoe UI Bold",
        fontsize=64,
        bold=True,
        italic=False,
        primary_color=_c(222, 248, 255),
        secondary_color=_c(0, 230, 255),
        outline_color=_c(0, 80, 110),
        back_color=_c(0, 0, 0, 76),
        outline=3.0,
        shadow=1.5,
        alignment=2,
        margin_v=42,
    ),
    "outro": KaraokeStyle(
        name="Outro",
        fontname="Segoe UI Bold",
        fontsize=42,
        bold=False,
        italic=False,
        primary_color=_c(200, 208, 230),
        secondary_color=_c(125, 132, 190),
        outline_color=_c(28, 34, 74),
        back_color=_c(0, 0, 0, 92),
        outline=2.2,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
    "ad_lib": KaraokeStyle(
        name="AdLib",
        fontname="Segoe UI Bold",
        fontsize=38,
        bold=True,
        italic=True,
        primary_color=_c(226, 255, 230),
        secondary_color=_c(92, 255, 130),
        outline_color=_c(0, 72, 34),
        back_color=_c(0, 0, 0, 100),
        outline=2.2,
        shadow=1.0,
        alignment=2,
        margin_v=42,
    ),
}
STYLE_DEFAULTS: dict[str, dict[str, str]] = {
    "intro": {"color": "soft", "effect": "fade_in"},
    "verse": {"color": "default", "effect": "highlight"},
    "prechorus": {"color": "warm", "effect": "highlight"},
    "chorus": {"color": "intense", "effect": "highlight"},
    "bridge": {"color": "cool", "effect": "highlight"},
    "drop": {"color": "warm", "effect": "highlight"},
    "outro": {"color": "warm", "effect": "fade_in"},
    "ad_lib": {"color": "soft", "effect": "none"},
}

PRESET_LIBRARY: dict[str, StylePreset] = {
    "default": StylePreset(
        id="default",
        label="Default",
        version=1,
        description="Clean professional karaoke subtitles.",
        styles=DEFAULT_STYLES,
    ),
    "neon": StylePreset(
        id="neon",
        label="Neon",
        version=1,
        description="Original neon karaoke subtitles.",
        styles=NEON_STYLES,
        effect_profile_id="soft_glow",
    ),
    "cyberpunk": StylePreset(
        id="cyberpunk",
        label="Cyberpunk",
        version=1,
        description="Premium synthwave karaoke subtitles.",
        styles=CYBERPUNK_STYLES,
        effect_profile_id="outline_pop",
    ),
    "section-coded": StylePreset(
        id="section-coded",
        label="Section Coded",
        version=1,
        description="Color-coded styles for song sections.",
        styles=SECTION_CODED_STYLES,
    ),
    "single-style-kf": StylePreset(
        id="single-style-kf",
        label="Single Style KF",
        version=1,
        description="One consistent visual style for every lyric section.",
        styles=SINGLE_STYLE_KF_STYLES,
        effect_profile_id="clean_sweep",
    ),
    "aegisub-classic-blue": StylePreset(
        id="aegisub-classic-blue",
        label="Aegisub Classic Blue",
        version=1,
        description="Classic fansub blue/cyan karaoke styling.",
        styles=AEGISUB_CLASSIC_BLUE_STYLES,
        effect_profile_id="clean_sweep",
    ),
    "aegisub-gold-chorus": StylePreset(
        id="aegisub-gold-chorus",
        label="Aegisub Gold Chorus",
        version=1,
        description="Warm white verses with gold hook emphasis.",
        styles=AEGISUB_GOLD_CHORUS_STYLES,
        effect_profile_id="soft_glow",
    ),
    "aegisub-anime-pop": StylePreset(
        id="aegisub-anime-pop",
        label="Aegisub Anime Pop",
        version=1,
        description="Bright pink, cyan, and yellow anime karaoke styling.",
        styles=AEGISUB_ANIME_POP_STYLES,
        effect_profile_id="bounce_word",
    ),
    "aegisub-soft-pastel": StylePreset(
        id="aegisub-soft-pastel",
        label="Aegisub Soft Pastel",
        version=1,
        description="Low-contrast mint, lavender, and rose subtitle styling.",
        styles=AEGISUB_SOFT_PASTEL_STYLES,
        effect_profile_id="clean_sweep",
    ),
    "aegisub-night-glow": StylePreset(
        id="aegisub-night-glow",
        label="Aegisub Night Glow",
        version=1,
        description="Cool white, blue, and purple glow-friendly styling.",
        styles=AEGISUB_NIGHT_GLOW_STYLES,
        effect_profile_id="soft_glow",
    ),
    "aegisub-impact-red": StylePreset(
        id="aegisub-impact-red",
        label="Aegisub Impact Red",
        version=1,
        description="High-impact white and red karaoke styling.",
        styles=AEGISUB_IMPACT_RED_STYLES,
        effect_profile_id="outline_pop",
    ),
    "aegisub-dual-vocal": StylePreset(
        id="aegisub-dual-vocal",
        label="Aegisub Dual Vocal",
        version=1,
        description="Lead vocal cyan with distinct ad-lib and bridge colors.",
        styles=AEGISUB_DUAL_VOCAL_STYLES,
        effect_profile_id="clean_sweep",
    ),
    "aegisub-clean-editorial": StylePreset(
        id="aegisub-clean-editorial",
        label="Aegisub Clean Editorial",
        version=1,
        description="Restrained editorial white, silver, and subtle gold styling.",
        styles=AEGISUB_CLEAN_EDITORIAL_STYLES,
        effect_profile_id="clean_sweep",
    ),
    "aegisub-cyber-minimal": StylePreset(
        id="aegisub-cyber-minimal",
        label="Aegisub Cyber Minimal",
        version=1,
        description="Minimal cyan and magenta styling with dark outlines.",
        styles=AEGISUB_CYBER_MINIMAL_STYLES,
        effect_profile_id="soft_glow",
    ),
    "aegisub-stage-lights": StylePreset(
        id="aegisub-stage-lights",
        label="Aegisub Stage Lights",
        version=1,
        description="White, blue, magenta, and gold stage-light palette.",
        styles=AEGISUB_STAGE_LIGHTS_STYLES,
        effect_profile_id="bounce_word",
    ),
}

PRESETS: dict[str, Mapping[str, KaraokeStyle]] = {
    preset.id: preset.styles for preset in PRESET_LIBRARY.values()
}

SECTION_TO_STYLE = {
    "intro": "intro",
    "introduction": "intro",
    "opening": "intro",
    "verse": "verse",
    "verse 1": "verse",
    "verse 2": "verse",
    "verse 3": "verse",
    "estrofe": "verse",
    "estrofa": "verse",
    "rap verse": "verse",
    "spoken": "verse",
    "spoken word": "verse",
    "pre-chorus": "prechorus",
    "pre chorus": "prechorus",
    "prechorus": "prechorus",
    "pre-chorus 2": "prechorus",
    "pre-hook": "prechorus",
    "lift": "prechorus",
    "build": "prechorus",
    "build-up": "prechorus",
    "buildup": "prechorus",
    "chorus": "chorus",
    "chorus 2": "chorus",
    "chorus 3": "chorus",
    "refrao": "chorus",
    "refrão": "chorus",
    "refrán": "chorus",
    "hook": "chorus",
    "hook 2": "chorus",
    "big chorus": "chorus",
    "final chorus": "chorus",
    "climax": "chorus",
    "drop": "drop",
    "drop 1": "drop",
    "drop 2": "drop",
    "bridge": "bridge",
    "ponte": "bridge",
    "breakdown": "bridge",
    "break": "bridge",
    "interlude": "bridge",
    "guitar solo": "bridge",
    "solo": "bridge",
    "instrumental": "bridge",
    "instrumental break": "bridge",
    "spoken bridge": "bridge",
    "dialogue": "bridge",
    "transition": "bridge",
    "middle 8": "bridge",
    "middle eight": "bridge",
    "outro": "outro",
    "outro chorus": "outro",
    "outro hook": "outro",
    "ending": "outro",
    "fade out": "outro",
    "fade-out": "outro",
    "coda": "outro",
}

LYRICS_SECTION_TO_STYLE: dict[str, str] = {
    "intro": "intro",
    "introduction": "intro",
    "opening": "intro",
    "outro": "outro",
    "outro chorus": "outro",
    "outro hook": "outro",
    "ending": "outro",
    "fade out": "outro",
    "fade-out": "outro",
    "coda": "outro",
    "verse": "verse",
    "verse 1": "verse",
    "verse 2": "verse",
    "verse 3": "verse",
    "estrofe": "verse",
    "estrofa": "verse",
    "rap verse": "verse",
    "spoken": "verse",
    "spoken word": "verse",
    "chorus": "chorus",
    "chorus 2": "chorus",
    "chorus 3": "chorus",
    "refrao": "chorus",
    "refrão": "chorus",
    "refrán": "chorus",
    "hook": "chorus",
    "hook 2": "chorus",
    "drop": "chorus",
    "drop 1": "chorus",
    "drop 2": "chorus",
    "big chorus": "chorus",
    "final chorus": "chorus",
    "climax": "chorus",
    "pre-chorus": "verse",
    "pre-chorus 2": "verse",
    "pre chorus": "verse",
    "pre-hook": "verse",
    "lift": "verse",
    "build": "verse",
    "build-up": "verse",
    "buildup": "verse",
    "bridge": "bridge",
    "ponte": "bridge",
    "breakdown": "bridge",
    "break": "bridge",
    "interlude": "bridge",
    "guitar solo": "bridge",
    "solo": "bridge",
    "instrumental": "bridge",
    "instrumental break": "bridge",
    "spoken bridge": "bridge",
    "dialogue": "bridge",
    "transition": "bridge",
    "middle 8": "bridge",
    "middle eight": "bridge",
}

_SECTION_PREFIX_FALLBACK: dict[str, str] = {
    "verse": "verse",
    "chorus": "chorus",
    "refra": "chorus",
    "hook": "chorus",
    "drop": "drop",
    "bridge": "bridge",
    "pont": "bridge",
    "break": "bridge",
    "interlude": "bridge",
    "intro": "intro",
    "outro": "outro",
    "pre": "prechorus",
    "build": "prechorus",
}

LYRICS_SECTION_PREFIX_FALLBACK: dict[str, str] = {
    "verse": "verse",
    "chorus": "chorus",
    "refra": "chorus",
    "hook": "chorus",
    "drop": "chorus",
    "bridge": "bridge",
    "pont": "bridge",
    "break": "bridge",
    "pre": "verse",
    "intro": "intro",
    "outro": "outro",
    "solo": "bridge",
    "interl": "bridge",
    "instru": "bridge",
    "build": "verse",
    "spoken": "verse",
    "coda": "outro",
}


def list_preset_ids() -> list[str]:
    return list(PRESET_LIBRARY.keys())


def get_preset(preset_id: str) -> StylePreset:
    try:
        return PRESET_LIBRARY[preset_id]
    except KeyError as exc:
        raise KeyError(f"Unknown karaoke style preset: {preset_id}") from exc


def list_animation_profile_ids() -> list[str]:
    return list(ANIMATION_PROFILES.keys())


def get_animation_profile(profile_id: str) -> AnimationProfile:
    try:
        return ANIMATION_PROFILES[profile_id]
    except KeyError as exc:
        raise KeyError(f"Unknown karaoke animation profile: {profile_id}") from exc


def list_animation_profile_metadata() -> list[dict[str, object]]:
    return [
        {
            "id": profile.id,
            "label": profile.label,
            "safety": profile.safety,
            "karaoke_tag": profile.karaoke_tag,
            "line_effects": list(profile.line_effects),
            "word_effects": list(profile.word_effects),
            "layer_strategy": profile.layer_strategy,
            "max_extra_layers": profile.max_extra_layers,
            "motion_intensity": profile.motion_intensity,
            "description": profile.description,
        }
        for profile in ANIMATION_PROFILES.values()
    ]


def list_preset_metadata() -> list[dict[str, object]]:
    return [
        {
            "id": preset.id,
            "label": preset.label,
            "version": preset.version,
            "description": preset.description,
            "styles": list(preset.styles.keys()),
            "effects": list(preset.effects),
            "effect_profile": preset.effect_profile_id,
        }
        for preset in PRESET_LIBRARY.values()
    ]


def supported_style_keys() -> set[str]:
    return set(STYLE_DEFAULTS.keys())


def is_supported_style(style: object) -> bool:
    return isinstance(style, str) and style in supported_style_keys()


def is_supported_effect(effect: object) -> bool:
    return isinstance(effect, str) and effect in SUPPORTED_EFFECTS


def resolve_section(label: str) -> tuple[str, str]:
    normalized = str(label or "").strip().lower()
    stripped = re.sub(r"[\s\d\(\)]+$", "", normalized).strip()
    if stripped and stripped != normalized and stripped in SECTION_TO_STYLE:
        return stripped, SECTION_TO_STYLE[stripped]
    if normalized in SECTION_TO_STYLE:
        return normalized, SECTION_TO_STYLE[normalized]

    for prefix, style in _SECTION_PREFIX_FALLBACK.items():
        if normalized.startswith(prefix):
            return normalized, style

    return normalized, DEFAULT_STYLE_KEY


def resolve_lyrics_section(label: str) -> tuple[str, str]:
    normalized = str(label or "").strip().lower()
    if normalized in LYRICS_SECTION_TO_STYLE:
        return normalized, LYRICS_SECTION_TO_STYLE[normalized]

    stripped = re.sub(r"[\s\d\(\)]+$", "", normalized).strip()
    if stripped and stripped in LYRICS_SECTION_TO_STYLE:
        return stripped, LYRICS_SECTION_TO_STYLE[stripped]

    for prefix, style in LYRICS_SECTION_PREFIX_FALLBACK.items():
        if normalized.startswith(prefix):
            return normalized, style

    return normalized, DEFAULT_STYLE_KEY


def validate_preset(preset: StylePreset) -> list[str]:
    errors: list[str] = []
    if not preset.id:
        errors.append("Preset is missing id")
    if not preset.label:
        errors.append(f"Preset {preset.id} is missing label")
    if preset.version < 1:
        errors.append(f"Preset {preset.id} has invalid version: {preset.version}")
    if not preset.styles:
        errors.append(f"Preset {preset.id} has no styles")
    if DEFAULT_STYLE_KEY not in preset.styles:
        errors.append(f"Preset {preset.id} is missing default style: {DEFAULT_STYLE_KEY}")
    for style_key, style in preset.styles.items():
        if not isinstance(style, KaraokeStyle):
            errors.append(f"Preset {preset.id} style {style_key} is not a KaraokeStyle")
    for effect in preset.effects:
        if not is_supported_effect(effect):
            errors.append(f"Preset {preset.id} has unsupported effect: {effect}")
    if preset.effect_profile_id not in ANIMATION_PROFILES:
        errors.append(f"Preset {preset.id} has unknown animation profile: {preset.effect_profile_id}")
    return errors


def validate_all_presets() -> list[str]:
    errors: list[str] = []
    for preset in PRESET_LIBRARY.values():
        errors.extend(validate_preset(preset))
    return errors
