"""
ass_builder.py — Logic for generating Advanced Substation Alpha (.ass) files.
Fast and synchronous.
No subprocess, no model calls.
"""
from __future__ import annotations
from typing import List, Tuple, Optional


# Clamp boundaries for word durations.
# MIN kept tight; MAX raised to 4.0s to accommodate sustained notes in metal/ballads.
# The old 1.20s cap was cutting highlights mid-note on long vowels ("heeere!").
MIN_WORD_S = 0.03   # 3 cs
MAX_WORD_S = 4.00   # 400 cs — matches CorrectorConfig.max_word_sec_voice


def clamp_duration(dur: float,
                   min_s: float = MIN_WORD_S,
                   max_s: float = MAX_WORD_S) -> float:
    """Prende a duracao de uma palavra entre o minimo e o maximo do karaoke.

    Estava inline em to_k_tags. Extraida de volta porque tests/test_ass_builder.py
    a importa pelo nome: a importacao quebrada interrompia a COLETA da suite
    inteira, entao nenhum teste do repositorio rodava sob `pytest tests/`.
    """
    return max(min_s, min(max_s, dur))

ASS_HEADER = """\
[Script Info]
; Script generated by Karaoke Pipeline
Title: Auto-aligned Karaoke
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1280
PlayResY: 720

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,60,&H00FFFFFF,&H0000FFFF,&H00000000,&H64000000,0,0,0,0,100,100,0,0,1,3,1,2,30,30,60,1
Style: Adlib,Cabin,46,&H00A0C8FF,&H0000FFFF,&H00000000,&H64000000,0,1,0,0,100,100,0,0,1,2,1,2,30,30,60,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

# Default screen position for lyrics (bottom-centre, 1280×720)
DEFAULT_POS = (640, 390)


def format_ass_time(seconds: float) -> str:
    """Convert float seconds to ASS timestamp H:MM:SS.cc"""
    if seconds < 0:
        seconds = 0
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = seconds % 60
    return f"{h}:{m:02d}:{s:05.2f}"


def to_k_tags(
    line_words: List[str],
    word_timings: List[Tuple[float, float, str]],
    min_s: float = MIN_WORD_S,
    max_s: float = MAX_WORD_S,
) -> Tuple[str, float, float]:
    """
    Build the {\\kf<cs>}word ... string for one lyric line.
    Uses \\kf (progressive fill) instead of \\k (hard jump).

    Args:
        line_words:    tokens from the lyrics file for this line
        word_timings:  (start, end, text) from forced aligner
    """
    if not word_timings:
        return "", 0, 0

    line_start = word_timings[0][0]
    line_end = word_timings[-1][1]
    
    k_parts = []
    for i, lw in enumerate(line_words):
        if i < len(word_timings):
            w_start, w_end, _ = word_timings[i]
            dur = clamp_duration(w_end - w_start, min_s, max_s)
            if i == 0:
                line_start = w_start
            line_end = w_end
            dur_cs = max(3, int(round(dur * 100)))
            k_parts.append(f"{{\\kf{dur_cs}}}{lw}")   # \\kf: progressive fill
        else:
            k_parts.append(lw)

    return " ".join(k_parts), line_start, line_end


def build_dialogue_event(
    line_words: List[str],
    word_timings: List[Tuple[float, float, str]],
    pos: Optional[Tuple[int, int]] = None,
    style: str = "Default",
    layer: int = 0,
) -> str:
    """
    Return a single Dialogue: line for an ASS event.

    Args:
        pos:   (x, y) screen position; uses DEFAULT_POS if None
        style: ASS style name ("Default" or "Adlib")
        layer: ASS layer (higher = rendered on top)
    """
    k_text, start, end = to_k_tags(line_words, word_timings)
    px, py = pos if pos is not None else DEFAULT_POS
    # \\an2 = bottom-centre anchor; \\pos overrides margin positioning
    override = f"{{\\an2\\pos({px},{py})}}"
    return (
        f"Dialogue: {layer},"
        f"{format_ass_time(start)},{format_ass_time(end)},"
        f"{style},,0,0,0,,{override}{k_text}"
    )


def group_words_by_lyrics_lines(
    lyrics_lines: List[str],
    all_words: list,   # List[Interval] from textgrid_parser
    min_s: float = MIN_WORD_S,
    max_s: float = MAX_WORD_S,
    pos: Optional[Tuple[int, int]] = None,
) -> List[str]:
    """
    Map lyric lines to aligned word timings and produce Dialogue: events.
    ``all_words`` is consumed sequentially — one timing per lyric token.
    """
    events: List[str] = []
    word_idx = 0

    for line in lyrics_lines:
        line_clean = line.strip()
        if not line_clean:
            continue
            
        # tokenize
        tokens = line_clean.split()
        if not tokens:
            continue

        n      = len(tokens)
        slice_ = all_words[word_idx : word_idx + n]
        timings = [(w.start, w.end, w.text) for w in slice_]
        word_idx += n
        
        event = build_dialogue_event(tokens, timings, pos=pos)
        events.append(event)

    return events


def write_ass(events: List[str]) -> str:
    """Return complete ASS file content as a string."""
    body = "\n".join(events) + "\n"
    return ASS_HEADER + body